version: '3.5'

services:
  auth-api:
    image: ${DOCKER_REGISTRY-}auth-api
    build:
      context: .
      args:
        - ASPNETCORE_ENVIRONMENT_ARG=Debug
      dockerfile: Auth-API/Dockerfile
    ports:     
      - "8081:80"
      - "8082:443"